name: Test private from public

on: [push]
  #schedule:
    #- cron:  '1,31 * * * *'

permissions:
  contents: write

jobs:
  urlscan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
