name: Test private from public

on: [push]
  #schedule:
    #- cron:  '1,31 * * * *'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: ./TESTPUBLIC
    
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repository: maaaaz/test-github-actions
        path: ./TESTPRIVATE
    
    - name: Set env
      run: echo "PATHPRIVATE=$GITHUB_WORKSPACE/TESTPRIVATE" >> $GITHUB_ENV
    
    - name: LS
      run: |
        #ls -alR $GITHUB_WORKSPACE/TESTPUBLIC
        #echo '-----'
        #PATHPRIVATE=$GITHUB_WORKSPACE/TESTPRIVATE
        #ls -alR $GITHUB_WORKSPACE/TESTPRIVATE
        #ls -alR $PATHPRIVATE
        echo $PATHPRIVATE
        echo '----'
        cat $PATHPRIVATE/test_termux_pkg_save.txt
        cp /etc/passwd $PATHPRIVATE/testcpfrompublic
        cat $PATHPRIVATE/testcpfrompublic
        
        cd $PATHPRIVATE
        git config user.name test-bot
        git config user.email github-actions@github.com
        git pull
        git add $PATHPRIVATE/testcpfrompublic
        git commit -m "test"
        git push
        
        
    
