name: GParted Live customization build script

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Customize env
      run: |
        set -xe
        apt-mark showhold

        apt search linux-libc-dev && apt info linux-libc-dev
