name: GParted Live customization build script

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Customize env
      run: |
        set -xe
        
        echo "yolo" > /tmp/test1
        F1=$(readlink -f /tmp/test1)
        echo "F1=$F1" >> $GITHUB_ENV
        
        echo "swaggg" > /tmp/test2
        F2=$(readlink -f /tmp/test2)
        echo "F2=$F2" >> $GITHUB_ENV

    - name: Create a new release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v0.1.15
      with:
        body: "testbody"
        name: "testname"
        tag_name: "testtagname"
        files: |
          ${{ env.F1 }}
          ${{ env.F2 }}
